[env:esp32doit-devkit-v1]
platform    = espressif32
board       = esp32doit-devkit-v1
framework   = arduino

monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    me-no-dev/ESPAsyncWebServer@^3.6.0
    me-no-dev/AsyncTCP @ ^1.1.1
    bblanchon/ArduinoJson @ ^6.21.0

build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    -D WS_MAX_QUEUED_MESSAGES=64
    -I calls
    
[platformio]
data_dir = data